### ISSUE TITLE
NNEF V-1.0.3 Support

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#321]
NNEF has fixed minor bugs in the Spec and released a new version.

* Match Model Compiler to V 1.0.3
* Most of the fixed issues were filled by us, so not major changes
* Test with the latest NNEF Version

**Comment by kiritigowda** [comment]
@hansely any updates on this? Check for 1.0.3 support.

**Comment by hansely** [comment]
I updated nnef to the latest version and ran the profile script and all the models were passing.
The new updates in V1.0.3 includes changes in min_max_linear_quantize node which is not supported by current nnef_to_nnir script. It will be added in the future since we don't have any models with min_max_linear_quantize node. 
Here is the result of profile script.

|alexnet-caffe   |  1|   6.176|   6.176
|alexnet-onnx    |  1|   4.220|   4.220
|vgg16-caffe     |  1|  60.477|  60.477
|vgg16-onnx      |  1|  12.445|  12.445
|vgg19-caffe     |  1|  48.834|  48.834
|vgg19-onnx      |  1|  14.153|  14.153
|googlenet-caffe |  1|  12.014|  12.014
|googlenet-onnx  |  1|   4.343|   4.343
|inceptionv1-onnx|  1|   4.957|   4.957
|inceptionv2-onnx|  1|   8.110|   8.110
|resnetv1-18-onnx|  1|   3.515|   3.515
|resnetv1-34-onnx|  1|   6.775|   6.775
|resnetv1-50-onnx|  1|   7.083|   7.083
|resnetv1-101-onnx|  1|  13.434|  13.434
|resnetv1-152-caffe|  1|  19.897|  19.897
|resnetv2-18-onnx|  1|   3.598|   3.598
|resnetv2-34-onnx|  1|   6.870|   6.870
|resnetv2-50-onnx|  1|   6.791|   6.791
|resnetv2-101-onnx|  1|  13.366|  13.366
|mobilenetv1-caffe|  1|   2.425|   2.425
|mobilenetv2-onnx|  1|   3.337|   3.337
|mobilenetv2-caffe|  1|   3.435|   3.435
|squeezenet1.0-caffe|  1|   7.862|   7.862
|squeezenet1.0-onnx|  1|   1.689|   1.689
|squeezenet1.1-caffe|  1|   5.090|   5.090
|squeezenet1.1-onnx|  1|   1.702|   1.702

**Comment by kiritigowda** [comment]
V-1.0.3 supported
