### ISSUE TITLE
AMD Media - Decode .264 elementary stream input

### ISSUE THREAD

**Issue by qianqing13579** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#459]
MIVision project gives a sample to show how to decode  MP4/JPEG input files. I have run it successfully.Now I want to use .264 elementary stream input to do decoding,but I do not konw how to do it.

**Comment by qianqing13579** [comment]
@rrawther ,can you give me a sample to show how to decode .264 elementary stream input by using amd_media？

**Comment by rrawther** [comment]
@qianqing13579 : We haven't tried elementary stream decoding using amd_media, because it uses ffmpeg api.  You can decode .mp4 files using runvx utility and a gdf. See the following

import vx_amd_media
data vid1 = scalar:STRING,"1,<file.mp4:0>"
data nvimg  = image:w,h,NV12
data loop = scalar:INT32,0
data opencl_out = scalar:INT32,0
node com.amd.amd_media.decode vid1 nvimg NULL loop opencl_out

**Comment by rrawther** [comment]
This issue is fixed. Please try the following gdf to decode elementary stream
import vx_amd_media
data vid1 = scalar:STRING,"1,file.264:0"
data nvimg = image:w,h,NV12:write,output.yuv
data loop = scalar:INT32,0
data opencl_out = scalar:INT32,0
node com.amd.amd_media.decode vid1 nvimg NULL loop opencl_out

runvx -frames:<#framestodecode> file decoder.gdf

Please view the output.yuv file for the decoded output in raw format or encode to mp4 using amd_media_encoder.

**Comment by rrawther** [comment]
@qianqing13579 @kiritigowda can you close this issue?
It is working in the develop branch
